version: "3.4"

services:

  apha-apps-perms-move-animal-ui:
    image: defradigital/apha-apps-perms-move-animal-ui:${MOVE_ANIMAL_UI:-latest}  # Override the version by setting an environment variable MOVE_ANIMAL_UI=version.to.run
    ports:
      - "3000:80"
    environment:
      - PORT=80

